# Installable packages using apt

utils:
  - git=1:2.39.2-1.1
  - vim=2:9.0.1378-2
  - avahi-daemon=0.8-10

python3:
  - python3=3.11.2-1+b1
  - python3-pyaudio=0.2.13-1+b1
  - python3-pip=23.0.1+dfsg-1+rpt1

clock: "{{ ansible_date_time.epoch }}"